/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.examples.hello.pulsar;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppTodo() {
        App classUnderTest = new App();
    }
}
